<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="15" total="16" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel test suite" duration-ms="81708" started-at="2017-09-13T15:23:31Z" finished-at="2017-09-13T15:24:53Z">
    <groups>
      <group name="2">
        <method signature="Login.assertElementsOnPage()[pri:0, instance:ui.Login@464bee09]" name="assertElementsOnPage" class="ui.Login"/>
      </group> <!-- 2 -->
      <group name="test">
        <method signature="Login.assertElementsOnPage()[pri:0, instance:ui.Login@464bee09]" name="assertElementsOnPage" class="ui.Login"/>
      </group> <!-- test -->
    </groups>
    <test name="functestForLoginPage" duration-ms="81708" started-at="2017-09-13T15:23:31Z" finished-at="2017-09-13T15:24:53Z">
      <class name="ui.Login">
        <test-method status="PASS" signature="before()[pri:0, instance:ui.Login@464bee09]" name="before" is-config="true" duration-ms="18503" started-at="2017-09-13T18:23:31Z" finished-at="2017-09-13T18:23:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="assertElementsOnPage()[pri:0, instance:ui.Login@464bee09]" name="assertElementsOnPage" duration-ms="55816" started-at="2017-09-13T18:23:50Z" finished-at="2017-09-13T18:24:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at ui.Login.assertElementsOnPage(Login.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertElementsOnPage -->
        <test-method status="PASS" signature="after()[pri:0, instance:ui.Login@464bee09]" name="after" is-config="true" duration-ms="3926" started-at="2017-09-13T18:24:49Z" finished-at="2017-09-13T18:24:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- ui.Login -->
    </test> <!-- functestForLoginPage -->
  </suite> <!-- Parallel test suite -->
</testng-results>
